package br.org.crea.commons.models.art.enuns;

public enum TipoBaixaArtEnum {

	CONCLUSAO(new Long(1)),
	RESCISAO_DE_CONTRATO(new Long(2)),
	RESCISAO_DE_CONTRATO_DO_PROFISSIONAL(new Long(3)),
	OUTROS(new Long(7)),
	EM_ANDAMENTO(new Long(8)),
	CANCELAMENTO_DA_ART(new Long(9)),
	SERVICO_PARALISADO(new Long(10)),
	SUBSTITUICAO_DE_RESPONSAVEL_TECNICO(new Long(11)),
	CANCELAMENTO_DE_REGISTRO_DO_PROFISSIONAL(new Long(12)),
	CANCELAMENTO_DE_REGISTRO_DA_EMPRESA(new Long(13)),
	ANULADA(new Long(14)),
	CANCELADA_POR_FALTA_DE_PAGAMENTO_ART_1025(new Long(15)),
	CANCELAMENTO_POR_SUBSTITUICAO_DE_ART(new Long(16)),
	FALECIMENTO(new Long(17)),
	INTERRUPCAO_DO_REGISTRO_DO_PROFISSIONAL(new Long(18)),
	BAIXA_DO_PROFISSIONAL_DO_QUADRO_TECNICO_DA_EMPRESA(new Long(19)),
	RESCISAO_FORMALIZADA(new Long(20)),
	RESCISAO_VERBAL_QUE_OCORRA_COM_A_CONCORDANCIA_DO_CONTRATANTE(new Long(21)),
	RESCISAO_VERBAL_QUE_OCORRA_SEM_A_CONCORDANCIA_DO_CONTRATANTE(new Long(22)),
	INTERRUPCAO_DE_OBRA_E_SERVICO_POR(new Long(23)),
	TRANSFERÊNCIA_PARA_CFT_DE_REGISTRO_DO_PROFISSIONAL(new Long(24));
	
	private final Long id;
		
	TipoBaixaArtEnum(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}
}
