
--------------------------------------------------------
--  DDL for Table CAD_ARQUIVOS
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."CAD_ARQUIVOS" 
   (	"ID" NUMBER, 
	"CAMINHO_ORIGINAL" VARCHAR2(60 BYTE), 
	"CAMINHO_STORAGE" VARCHAR2(60 BYTE), 
	"NOME_ORIGINAL" VARCHAR2(60 BYTE), 
	"NOME_STORAGE" VARCHAR2(60 BYTE), 
	"EXTENSAO" VARCHAR2(6 BYTE), 
	"TAMANHO" NUMBER, 
	"MODULO_SISTEMA" VARCHAR2(24 BYTE), 
	"DATA_INCLUSAO" DATE, 
	"FK_ID_PESSOA" NUMBER, 
	"STATUS" CHAR(1 BYTE), 
	"DESCRICAO" VARCHAR2(200 BYTE), 
	"PRIVADO" NUMBER DEFAULT 0, 
	"URI" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARQUIVO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."ARQUIVO_PK" ON "CORPORATIVO"."CAD_ARQUIVOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ARQUIVO_NOME_STORAGE
--------------------------------------------------------

  CREATE INDEX "CORPORATIVO"."IDX_ARQUIVO_NOME_STORAGE" ON "CORPORATIVO"."CAD_ARQUIVOS" ("NOME_STORAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CAD_ARQUIVOS
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CAD_ARQUIVOS" ADD CONSTRAINT "ARQUIVO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CAD_ARQUIVOS" MODIFY ("ID" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table SIACOL_ANEXO_ITEM_PAUTA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_ANEXO_ITEM_PAUTA" 
   (	"ID" NUMBER, 
	"FK_ARQUIVO" NUMBER, 
	"FK_ITEM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_ASSUNTO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_ASSUNTO" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(100 BYTE), 
	"ATIVO" VARCHAR2(1 BYTE), 
	"CODIGO" NUMBER, 
	"FK_ASSUNTO_CONFEA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_ASSUNTO_CONFEA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_ASSUNTO_CONFEA" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(100 BYTE), 
	"ATIVO" VARCHAR2(1 BYTE), 
	"CODIGO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_CONFIG_PESSOA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_CONFIG_PESSOA" 
   (	"ID" NUMBER, 
	"FK_FUNCIONARIO" NUMBER, 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"ATIVO" NUMBER(1,0), 
	"FK_ID_DEPARTAMENTO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_DOCUMENTO_PROTOCOLO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_DOCUMENTO_PROTOCOLO" 
   (	"ID" NUMBER, 
	"FK_DOCUMENTO" NUMBER, 
	"FK_PROTOCOLO" NUMBER, 
	"ITEM" VARCHAR2(100 BYTE), 
	"DS_ITEM" VARCHAR2(2000 BYTE), 
	"FK_STATUS" NUMBER DEFAULT 0, 
	"FK_PESSOA_DESTAQUE" NUMBER, 
	"FK_PESSOA_VISTA" NUMBER, 
	"EM_VOTACAO" NUMBER DEFAULT 0, 
	"TEM_EXTRA_PAUTA" NUMBER DEFAULT 0, 
	"TEM_FILHO" NUMBER DEFAULT 0, 
	"OBS_REUNIAO" VARCHAR2(1000 BYTE), 
	"PERGUNTA" VARCHAR2(1000 BYTE), 
	"SOLICITACAO_VISTA" NUMBER DEFAULT 0, 
	"SOLICITACAO_DESTAQUE" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_HABILIDADE_PESSOA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_HABILIDADE_PESSOA" 
   (	"ID" NUMBER, 
	"FK_PESSOA" NUMBER, 
	"FK_ASSUNTO" NUMBER, 
	"FK_DEPARTAMENTO" NUMBER, 
	"ATIVO" NUMBER(1,0), 
	"FK_ASSUNTO_SIACOL" NUMBER, 
	"PESSOA_LIBERADA" NUMBER(1,0) DEFAULT 1
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_HIST_PROTOCOLO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_HIST_PROTOCOLO" 
   (	"ID" NUMBER, 
	"FK_SIACOL_PROTOCOLO" NUMBER, 
	"DT_CREATE" DATE, 
	"FK_SIACOL_TIPO_HIST" NUMBER, 
	"FK_SIACOL_DOCUMENTO" NUMBER, 
	"FK_SIACOL_ID_PESSOA" NUMBER, 
	"DS_NOME_PESSOA" VARCHAR2(100 BYTE), 
	"FK_RESPONSAVEL_ATUAL" NUMBER, 
	"FK_RESPONSAVEL_NOVO" NUMBER, 
	"DS_RESPONSAVEL_NOVO" VARCHAR2(100 BYTE), 
	"HISTORICO" VARCHAR2(200 BYTE), 
	"DS_RESPONSAVEL_ATUAL" VARCHAR2(100 BYTE), 
	"FK_ASSUNTO_CORPORATIVO" NUMBER, 
	"DS_ASSUNTO_CORPORATIVO" VARCHAR2(100 BYTE), 
	"FK_ASSUNTO_SIACOL" NUMBER, 
	"DS_ASSUNTO_SIACOL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_PARTE_TEXTO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_PARTE_TEXTO" 
   (	"ID" NUMBER, 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"ATIVO" NUMBER(1,0), 
	"ORDEM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_PROTOCOLO_EXIGENCIA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_EXIGENCIA" 
   (	"MOTIVO" VARCHAR2(200 BYTE), 
	"TIPO_CONTATO" VARCHAR2(200 BYTE), 
	"PESSOA_CONTATO" VARCHAR2(400 BYTE), 
	"DT_CONTATO" DATE, 
	"ID" NUMBER, 
	"DT_INICIO" DATE, 
	"DT_FIM" DATE, 
	"FK_PROTOCOLO_SIACOL" NUMBER, 
	"FK_ARQUIVO" NUMBER, 
	"DESCRICAO" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_PROTOCOLO_RESPONSAVEL
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" 
   (	"ID" NUMBER, 
	"FK_PROTOCOLO_PAI" NUMBER, 
	"FK_PROTOCOLO_FILHO" NUMBER, 
	"FK_RESPONSAVEL" NUMBER, 
	"IMPORTADO" NUMBER(1,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_PROTOCOLOS
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" 
   (	"ID" NUMBER, 
	"NO_PROTOCOLO" NUMBER, 
	"NO_PROCESSO" NUMBER, 
	"FK_SITUACAO_PROTOCOLO" NUMBER, 
	"FK_DEPARTAMENTO" NUMBER, 
	"OBSERVACAO" VARCHAR2(500 BYTE), 
	"FK_ASSUNTO" NUMBER, 
	"DT_CADASTRO" DATE, 
	"FK_INTERESSADO" NUMBER, 
	"FK_ASSUNTO_SIACOL" NUMBER, 
	"DS_INTERESSADO" VARCHAR2(200 BYTE), 
	"DS_ASSUNTO" VARCHAR2(200 BYTE), 
	"FK_RESPONSAVEL" NUMBER, 
	"DS_RESPONSAVEL" VARCHAR2(200 BYTE), 
	"DT_SIACOL" DATE, 
	"DS_TIPO_ASSUNTO" VARCHAR2(100 BYTE), 
	"IMPORTADO" NUMBER(1,0) DEFAULT 0, 
	"ATIVO" NUMBER(1,0) DEFAULT 1, 
	"RECEBIDO" NUMBER(1,0) DEFAULT 0, 
	"DS_MOTIVO_DEVOLUCAO" VARCHAR2(50 BYTE), 
	"DS_JUSTIFICATIVA" VARCHAR2(500 BYTE), 
	"DT_RECEBIMENTO" DATE, 
	"FK_ANALISTA" NUMBER, 
	"DIGITALIZADO" NUMBER(1,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"FK_CONSELHEIRO_RELATOR" NUMBER, 
	"DS_CONSELHEIRO_RELATOR" VARCHAR2(200 BYTE), 
	"CLASSIFICACAO" VARCHAR2(30 BYTE) DEFAULT (null), 
	"FK_CONSELHEIRO_DEVOLUCAO" NUMBER, 
	"FK_EXIGENCIA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_PRT_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_PRT_DOCUMENTO" 
   (	"ID" NUMBER, 
	"FK_PESSOA_EMISSOR" NUMBER, 
	"FK_PESSOA_RECEPTOR" NUMBER, 
	"FK_SIACOL_PROTOCOLO" NUMBER, 
	"FK_SIACOL_TIPO_DOCUMENTO" NUMBER, 
	"DT_CREATE" DATE, 
	"DT_UPDATE" DATE, 
	"OBSERVACAO" VARCHAR2(500 BYTE), 
	"STATUS" CHAR(1 BYTE), 
	"DOCUMENTO" CLOB, 
	"ASSINADO" NUMBER(1,0), 
	"HASH" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DOCUMENTO") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SIACOL_REUNIAO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_REUNIAO" 
   (	"ID" NUMBER, 
	"FK_DEPARTAMENTO" NUMBER, 
	"DS_LOCAL" VARCHAR2(200 BYTE), 
	"TIPO" NUMBER, 
	"VIRTUAL" NUMBER, 
	"DATA_REUNIAO" DATE, 
	"HR_INICIO" DATE, 
	"HR_FIM" DATE, 
	"PRAZO" NUMBER, 
	"STATUS" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"FK_DOCUMENTO" NUMBER, 
	"QUORUM" NUMBER DEFAULT 0, 
	"FK_EXTRA_PAUTA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_REUNIAO_PRESENCA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_REUNIAO_PRESENCA" 
   (	"ID" NUMBER, 
	"FK_REUNIAO" NUMBER, 
	"FK_PESSOA" NUMBER, 
	"HORA_ENTREGA_CRACHA" DATE, 
	"HORA_DEVOLUCAO_CRACHA" DATE, 
	"PAPEL" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_RL_ASSUNTOS
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_RL_ASSUNTOS" 
   (	"FK_ASSUNTO_SIACOL" NUMBER, 
	"FK_PRT_ASSUNTO" NUMBER, 
	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_RL_COORD_DP
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_RL_COORD_DP" 
   (	"FK_PESSOA" NUMBER, 
	"FK_DEPARTAMENTO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_RL_DOCUMENTO_EMAIL
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_RL_DOCUMENTO_EMAIL" 
   (	"ID" NUMBER, 
	"FK_DOCUMENTO" NUMBER, 
	"FK_EMAIL_ENVIO" NUMBER, 
	"GRUPO_DESTINATARIOS" VARCHAR2(50 BYTE), 
	"EVENTO" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_RL_REUNIAO_EMAIL
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_RL_REUNIAO_EMAIL" 
   (	"ID" NUMBER, 
	"FK_REUNIAO" NUMBER, 
	"FK_EMAIL_ENVIO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_STATUS_ITEM_PAUTA
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_STATUS_ITEM_PAUTA" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_TIPO_DOCUMENTO" 
   (	"ID" NUMBER, 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"ATIVO" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_TIPO_HIST_PROTOCOLO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_TIPO_HIST_PROTOCOLO" 
   (	"ID" NUMBER, 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"ATIVO" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_TIPO_JULGAMENTO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(100 BYTE), 
	"DS_TIPO_JULGAMENTO" VARCHAR2(200 BYTE), 
	"ATIVO" NUMBER(1,0), 
	"CODIGO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIACOL_VOTO_REUNIAO
--------------------------------------------------------

  CREATE TABLE "CORPORATIVO"."SIACOL_VOTO_REUNIAO" 
   (	"ID" NUMBER, 
	"FK_REUNIAO" NUMBER, 
	"FK_PROTOCOLO" NUMBER, 
	"FK_PESSOA" NUMBER, 
	"VOTO" VARCHAR2(20 BYTE), 
	"DS_JUSTIFICATIVA" VARCHAR2(200 BYTE), 
	"DATA_VOTO" DATE, 
	"DESTAQUE" NUMBER(1,0) DEFAULT 0, 
	"ITEM" VARCHAR2(100 BYTE), 
	"DS_ITEM" VARCHAR2(500 BYTE), 
	"FK_ITEM_PAUTA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_ANEXO_ITEM_PAUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_ANEXO_ITEM_PAUTA_PK" ON "CORPORATIVO"."SIACOL_ANEXO_ITEM_PAUTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_ASSUNTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_ASSUNTO_PK" ON "CORPORATIVO"."SIACOL_ASSUNTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_ASSUNTO_CONFEA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_ASSUNTO_CONFEA_PK" ON "CORPORATIVO"."SIACOL_ASSUNTO_CONFEA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_CONFIG_PESSOA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_CONFIG_PESSOA_PK" ON "CORPORATIVO"."SIACOL_CONFIG_PESSOA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_DOCUMENTO_PROTOCOLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_DOCUMENTO_PROTOCOLO_PK" ON "CORPORATIVO"."SIACOL_DOCUMENTO_PROTOCOLO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_HABILIDADE_PESSOA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_HABILIDADE_PESSOA_PK" ON "CORPORATIVO"."SIACOL_HABILIDADE_PESSOA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_PARTE_TEXTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_PARTE_TEXTO_PK" ON "CORPORATIVO"."SIACOL_PARTE_TEXTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_PROTOCOLO_EXIGENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_PROTOCOLO_EXIGENCIA_PK" ON "CORPORATIVO"."SIACOL_PROTOCOLO_EXIGENCIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROTOCOLO_RESPONSAVEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."PK_PROTOCOLO_RESPONSAVEL" ON "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_PROTOCOLOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_PROTOCOLOS_PK" ON "CORPORATIVO"."SIACOL_PROTOCOLOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_FK_PROTOCOLOS_SIACOL
--------------------------------------------------------

  CREATE INDEX "CORPORATIVO"."IDX_FK_PROTOCOLOS_SIACOL" ON "CORPORATIVO"."SIACOL_PROTOCOLOS" ("NO_PROTOCOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_PRT_DOCUMENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_PRT_DOCUMENTOS_PK" ON "CORPORATIVO"."SIACOL_PRT_DOCUMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_REUNIAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_REUNIAO_PK" ON "CORPORATIVO"."SIACOL_REUNIAO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_RL_ASSUNTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_RL_ASSUNTOS_PK" ON "CORPORATIVO"."SIACOL_RL_ASSUNTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_RL_DOCUMENTO__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_RL_DOCUMENTO__PK" ON "CORPORATIVO"."SIACOL_RL_DOCUMENTO_EMAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_RL_REUNIAO_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_RL_REUNIAO_EMAIL_PK" ON "CORPORATIVO"."SIACOL_RL_REUNIAO_EMAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_STATUS_ITEM_PAUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_STATUS_ITEM_PAUTA_PK" ON "CORPORATIVO"."SIACOL_STATUS_ITEM_PAUTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_TIPO_TEXTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_TIPO_TEXTO_PK" ON "CORPORATIVO"."SIACOL_TIPO_DOCUMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_TIPO_HIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_TIPO_HIST_PK" ON "CORPORATIVO"."SIACOL_TIPO_HIST_PROTOCOLO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."TABLE1_PK" ON "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."UNIQUE_CODIGO" ON "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIACOL_VOTO_REUNIAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORPORATIVO"."SIACOL_VOTO_REUNIAO_PK" ON "CORPORATIVO"."SIACOL_VOTO_REUNIAO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SIACOL_STATUS_DOCUMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CORPORATIVO"."SIACOL_STATUS_DOCUMENTO" 
BEFORE UPDATE
ON SIACOL_PRT_DOCUMENTO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
IF :NEW.STATUS is null THEN
    :NEW.STATUS := 'A';
END IF;
END;
/
ALTER TRIGGER "CORPORATIVO"."SIACOL_STATUS_DOCUMENTO" ENABLE;
--------------------------------------------------------
--  Constraints for Table SIACOL_ANEXO_ITEM_PAUTA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_ANEXO_ITEM_PAUTA" ADD CONSTRAINT "SIACOL_ANEXO_ITEM_PAUTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_ANEXO_ITEM_PAUTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_ASSUNTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_ASSUNTO" ADD CONSTRAINT "SIACOL_ASSUNTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_ASSUNTO" ADD CONSTRAINT "SIACOL_ASSUNTO_UNIQUE" UNIQUE ("CODIGO") DISABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_ASSUNTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_ASSUNTO_CONFEA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_ASSUNTO_CONFEA" ADD CONSTRAINT "SIACOL_ASSUNTO_CONFEA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_ASSUNTO_CONFEA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_CONFIG_PESSOA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_CONFIG_PESSOA" ADD CONSTRAINT "SIACOL_CONFIG_PESSOA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_CONFIG_PESSOA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_DOCUMENTO_PROTOCOLO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_DOCUMENTO_PROTOCOLO" ADD CONSTRAINT "SIACOL_DOCUMENTO_PROTOCOLO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_DOCUMENTO_PROTOCOLO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_HABILIDADE_PESSOA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_HABILIDADE_PESSOA" ADD CONSTRAINT "SIACOL_HABILIDADE_PESSOA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_HABILIDADE_PESSOA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_HIST_PROTOCOLO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_HIST_PROTOCOLO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_PARTE_TEXTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_PARTE_TEXTO" ADD CONSTRAINT "SIACOL_PARTE_TEXTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PARTE_TEXTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_PROTOCOLO_EXIGENCIA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_EXIGENCIA" ADD CONSTRAINT "SIACOL_PROTOCOLO_EXIGENCIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_EXIGENCIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_PROTOCOLO_RESPONSAVEL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" ADD CONSTRAINT "PK_PROTOCOLO_RESPONSAVEL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" MODIFY ("FK_PROTOCOLO_PAI" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" MODIFY ("FK_PROTOCOLO_FILHO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLO_RESPONSAVEL" MODIFY ("FK_RESPONSAVEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_PROTOCOLOS
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" ADD CONSTRAINT "SIACOL_PROTOCOLOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" ADD CONSTRAINT "SIACOL_PROTOCOLOS_UNIQUE" UNIQUE ("NO_PROTOCOLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" MODIFY ("NO_PROTOCOLO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PROTOCOLOS" MODIFY ("NO_PROCESSO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_PRT_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_PRT_DOCUMENTO" ADD CONSTRAINT "SIACOL_PRT_DOCUMENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_PRT_DOCUMENTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_REUNIAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_REUNIAO" ADD CONSTRAINT "SIACOL_REUNIAO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_REUNIAO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_REUNIAO_PRESENCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_REUNIAO_PRESENCA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_RL_ASSUNTOS
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_RL_ASSUNTOS" ADD CONSTRAINT "SIACOL_RL_ASSUNTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_RL_ASSUNTOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_RL_DOCUMENTO_EMAIL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_RL_DOCUMENTO_EMAIL" ADD CONSTRAINT "SIACOL_RL_DOCUMENTO__PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_RL_DOCUMENTO_EMAIL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_RL_REUNIAO_EMAIL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_RL_REUNIAO_EMAIL" ADD CONSTRAINT "SIACOL_RL_REUNIAO_EMAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_RL_REUNIAO_EMAIL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_STATUS_ITEM_PAUTA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_STATUS_ITEM_PAUTA" ADD CONSTRAINT "SIACOL_STATUS_ITEM_PAUTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_STATUS_ITEM_PAUTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_TIPO_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_DOCUMENTO" ADD CONSTRAINT "SIACOL_TIPO_TEXTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_DOCUMENTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_TIPO_HIST_PROTOCOLO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_HIST_PROTOCOLO" ADD CONSTRAINT "SIACOL_TIPO_HIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_HIST_PROTOCOLO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIACOL_TIPO_JULGAMENTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_TIPO_JULGAMENTO" ADD CONSTRAINT "UNIQUE_CODIGO" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIACOL_VOTO_REUNIAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."SIACOL_VOTO_REUNIAO" ADD CONSTRAINT "SIACOL_VOTO_REUNIAO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CORPORATIVO"."SIACOL_VOTO_REUNIAO" MODIFY ("ID" NOT NULL ENABLE);
  
  
  
  --------------------------------------------------------
--  DDL for Sequence SIACOL_ITEM_PAUTA_ANEXOS_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SIACOL_ITEM_PAUTA_ANEXOS_SQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CAD_ARQUIVOS
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_CAD_ARQUIVOS"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CAD_AUDITORIA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_CAD_AUDITORIA"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 2201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CAD_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_CAD_DOCUMENTO"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1701 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CAD_ENVIO_EMAIL
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_CAD_ENVIO_EMAIL"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CAD_TIPO_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_CAD_TIPO_DOCUMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_HABILIDADE_PESSOA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_HABILIDADE_PESSOA"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 3383 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_RL_ARQUIVO_REUNIAO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_RL_ARQUIVO_REUNIAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_RL_ASSUNTOS
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_RL_ASSUNTOS"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 724 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_RL_DOCUMENTO_PROTOCOLO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_RL_DOCUMENTO_PROTOCOLO"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1310 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_RL_EMAIL_REUNIAO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_RL_EMAIL_REUNIAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_RL_PROTOCOLO_RESPONSAVEL
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_RL_PROTOCOLO_RESPONSAVEL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 40 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_ANEXO_ITEM_PAUTA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_ANEXO_ITEM_PAUTA"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_ASSUNTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_ASSUNTO"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 262 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_ASSUNTO_CONFEA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_ASSUNTO_CONFEA"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 182 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_CONFIG_PESSOA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_CONFIG_PESSOA"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 1040 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_EMAIL_CONSELHEIRO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_EMAIL_CONSELHEIRO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_HIST_PRT
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_HIST_PRT"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_PADRAO_TEXTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_PADRAO_TEXTO"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_PARTE_TEXTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_PARTE_TEXTO"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_PROTOCOLO_EXIGENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_PROTOCOLO_EXIGENCIA"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_PROTOCOLOS
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_PROTOCOLOS"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 61582 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_PRT_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_PRT_DOCUMENTO"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_REUNIAO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_REUNIAO"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_REUNIAO_PRESENCA
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_REUNIAO_PRESENCA"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 361 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_TIPO_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_TIPO_DOCUMENTO"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_TIPO_JULGAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_TIPO_JULGAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SIACOL_VOTO_REUNIAO
--------------------------------------------------------

   CREATE SEQUENCE  "CORPORATIVO"."SQ_SIACOL_VOTO_REUNIAO"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE ;

   
   --------------------------------------------------------
--  DDL for Function GETRESPONSAVELSIACOL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CORPORATIVO"."GETRESPONSAVELSIACOL" 
( ID_DEPARTAMENTO IN NUMBER , ID_ASSUNTO IN NUMBER ) 
        RETURN NUMBER 
    IS
        ID_RESPONSAVEL NUMBER;
BEGIN
    begin
            SELECT FK_PESSOA INTO ID_RESPONSAVEL FROM (
            SELECT FK_PESSOA, NVL(TB1.QTD,0) QTD FROM SIACOL_HABILIDADE_PESSOA,
                ( SELECT FK_RESPONSAVEL, COUNT(*) QTD FROM SIACOL_PROTOCOLOS 
                    WHERE FK_ASSUNTO = ID_ASSUNTO
                    AND FK_DEPARTAMENTO = ID_DEPARTAMENTO
                    AND TO_CHAR(DT_SIACOL,'DD/MM/YY') = TO_CHAR(SYSDATE,'DD/MM/YY')  
                    GROUP BY FK_RESPONSAVEL )TB1 
                WHERE TB1.FK_RESPONSAVEL(+) = FK_PESSOA  
                    AND FK_ASSUNTO = ID_ASSUNTO
                    AND FK_DEPARTAMENTO = ID_DEPARTAMENTO
                GROUP BY FK_PESSOA, NVL(TB1.QTD,0), TB1.QTD, 0, TB1.FK_RESPONSAVEL 
                ORDER BY QTD ASC
            ) TB2 WHERE ROWNUM <= 1;
            exception
            when no_data_found then
                RETURN 0;
            when others then
                RETURN 0;
    end;
        RETURN ID_RESPONSAVEL;

END ;

/
--------------------------------------------------------
--  DDL for Function GETANALISTASIACOL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CORPORATIVO"."GETANALISTASIACOL" 
( ID_DEPARTAMENTO IN NUMBER , ID_ASSUNTO IN NUMBER ) 
        RETURN NUMBER 
    IS
        ID_RESPONSAVEL NUMBER;
BEGIN
    begin
            SELECT FK_PESSOA INTO ID_RESPONSAVEL FROM (
            SELECT FK_PESSOA, NVL(TB1.QTD,0) QTD FROM SIACOL_HABILIDADE_PESSOA,
                ( SELECT FK_RESPONSAVEL, COUNT(*) QTD FROM SIACOL_PROTOCOLOS 
                    WHERE FK_ASSUNTO = ID_ASSUNTO
                    AND FK_DEPARTAMENTO = ID_DEPARTAMENTO
                    AND TO_CHAR(DT_SIACOL,'DD/MM/YY') = TO_CHAR(SYSDATE,'DD/MM/YY')  
                    GROUP BY FK_RESPONSAVEL )TB1 
                WHERE TB1.FK_RESPONSAVEL(+) = FK_PESSOA  
                    AND FK_ASSUNTO = ID_ASSUNTO
                    AND FK_DEPARTAMENTO = ID_DEPARTAMENTO
                GROUP BY FK_PESSOA, NVL(TB1.QTD,0), TB1.QTD, 0, TB1.FK_RESPONSAVEL 
                ORDER BY QTD ASC
            ) TB2 WHERE ROWNUM <= 1;
            exception
            when no_data_found then
                RETURN 0;
            when others then
                RETURN 0;
    end;
        RETURN ID_RESPONSAVEL;

END ;

/
--------------------------------------------------------
--  DDL for Function DISTRIBUICAO_IMPORTACAO_SIACOL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CORPORATIVO"."DISTRIBUICAO_IMPORTACAO_SIACOL" 
( ID_DEPARTAMENTO IN NUMBER) 
        RETURN NUMBER 
    IS
        BOOLEAN NUMBER;
        CURSOR CMOVIMENTOS IS
        --SELECT * FROM PRT_MOVIMENTOS WHERE DESPACHADO = 0 AND FK_ID_DESTINO_DEPARTAMENTOS = ID_DEPARTAMENTO AND FK_ID_SITUACOES <> 3 AND TO_CHAR(DATAENVIO,'YYYY') >=  TO_CHAR(SYSDATE-365,'YYYY');
        --SELECT PM.* FROM PRT_MOVIMENTOS PM, PRT_PROTOCOLOS P WHERE   P.ID = PM.FK_ID_PROTOCOLOS AND P.ULTIMOMOVIMENTO = PM.ID AND PM.FK_ID_DESTINO_DEPARTAMENTOS = ID_DEPARTAMENTO;
         SELECT PM.* FROM PRT_MOVIMENTOS PM, PRT_PROTOCOLOS P 
            WHERE   P.ID = PM.FK_ID_PROTOCOLOS 
                AND P.ULTIMOMOVIMENTO = PM.ID 
                AND PM.FK_ID_DESTINO_DEPARTAMENTOS = 1205
                AND P.FK_ID_ASSUNTOS IN ( SELECT ID FROM PRT_ASSUNTOS WHERE REMOVIDO = 0 AND ID = P.FK_ID_ASSUNTOS)
                AND ROWNUM < 11
                ORDER BY PM.FK_ID_PROTOCOLOS DESC ;
        V_NAO_EXISTE NUMBER;
        V_ERRO NUMBER;
        V_PROTOCOLO PRT_PROTOCOLOS%ROWTYPE;
        V_SIACOL_PROTOCOLO SIACOL_PROTOCOLOS%ROWTYPE;
        V_INTERESSADO CAD_PESSOAS%ROWTYPE;
        V_NOME SIACOL_PROTOCOLOS.DS_INTERESSADO%TYPE;
        V_ASSUNTO PRT_ASSUNTOS%ROWTYPE;
        V_IDRESPONSAVEL SIACOL_HABILIDADE_PESSOA.FK_PESSOA%TYPE;
        V_RESPONSAVEL SIACOL_PROTOCOLOS.DS_RESPONSAVEL%TYPE;
        V_SITUACAOPROTOCOLO SIACOL_PROTOCOLOS.FK_SITUACAO_PROTOCOLO%TYPE;
        V_IDPESSOA CAD_FUNCIONARIOS.FK_ID_PESSOAS_FISICAS%TYPE;
BEGIN
        FOR VMOVI IN CMOVIMENTOS LOOP
        
                V_ERRO := 0;
                V_NAO_EXISTE:= 0;

                -- Verifica se já existe um protocolo dentro do SIACOL
                BEGIN
                 V_NAO_EXISTE := 1;
                 SELECT * INTO V_SIACOL_PROTOCOLO FROM SIACOL_PROTOCOLOS WHERE NO_PROTOCOLO = VMOVI.FK_ID_PROTOCOLOS;                  
                EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                  V_NAO_EXISTE := 0;     
                  WHEN OTHERS THEN
                  V_ERRO:= 1;
                  V_NAO_EXISTE := 0; 
                END;
        
                IF V_NAO_EXISTE <> 1 THEN   
                    --DEVOLVE O PROTOCOLO SE FOR DO SIACOL E ESTIVER VOLTANDO PARA O MESMO DEPARTAMENTO( MUDANÇA DE STATUS )
                    IF V_SIACOL_PROTOCOLO.FK_DEPARTAMENTO = VMOVI.FK_ID_DESTINO_DEPARTAMENTOS THEN           
                        UPDATE SIACOL_PROTOCOLOS
                          SET FK_SITUACAO_PROTOCOLO = 2
                        WHERE ID = V_SIACOL_PROTOCOLO.ID;
                        V_ERRO:= 1; 
                    END IF;
                 END IF;
                --SE NAO FOR DO SIACOL OU SE FOI ENCAMINHADO PARA OUTRO DEPARTAMENTO ELE FAZ A DISTRIBUIÇÃO        
                IF V_ERRO = 0 AND V_NAO_EXISTE = 0 THEN 
        
                   -- PEGA O PROTOCOLO, INTERESSADO E ASSUNTO PARA POPULAR FK E DS;
                    SELECT * INTO V_PROTOCOLO FROM PRT_PROTOCOLOS WHERE NUMERO = VMOVI.FK_ID_PROTOCOLOS;
                    BEGIN
                        SELECT * INTO V_INTERESSADO FROM CAD_PESSOAS WHERE CODIGO = V_PROTOCOLO.FK_ID_PESSOAS;
                        EXCEPTION
                          WHEN NO_DATA_FOUND THEN
                          SELECT * INTO V_INTERESSADO FROM CAD_PESSOAS WHERE CODIGO = 0;
                          WHEN TOO_MANY_ROWS THEN
                          SELECT * INTO V_INTERESSADO FROM CAD_PESSOAS WHERE CODIGO = 0; 
                          WHEN OTHERS THEN
                          SELECT * INTO V_INTERESSADO FROM CAD_PESSOAS WHERE CODIGO = 0;
                    END;   
                    
                    
                    --SELECT * INTO V_ASSUNTO FROM PRT_ASSUNTOS WHERE CODIGO = V_PROTOCOLO.FK_ID_ASSUNTOS;
        
                    --PEGA A DESCRICAO DO INTERESSADO CONFORME O TIPO PESSOA;
                    begin
                        SELECT * INTO V_NOME FROM (
                            SELECT NOME FROM CAD_PESSOAS_FISICAS WHERE CODIGO = V_PROTOCOLO.FK_ID_PESSOAS
                                UNION 
                            SELECT DESCRICAO FROM CAD_RAZOES_SOCIAIS WHERE FK_CODIGO_PJS = V_PROTOCOLO.FK_ID_PESSOAS AND ATIVO = 1 AND FK_CODIGO_PJS is not null
                        ) TMP;
                        EXCEPTION
                          WHEN NO_DATA_FOUND THEN
                          V_NOME := 'NÃO INFORMADO'; 
                          WHEN TOO_MANY_ROWS THEN
                          V_NOME := 'NÃO INFORMADO'; 
                          WHEN OTHERS THEN
                          V_NOME := 'NÃO INFORMADO'; 
                    END;                    
                    
                    V_IDRESPONSAVEL := 0;
                    V_IDPESSOA := 0; 
                    V_SITUACAOPROTOCOLO := 17;
                    
                    -- Não insere nenhuma pessoa responsavel, esses responsáveis serão atualizados manualmente
                    SELECT NOME INTO V_RESPONSAVEL FROM CAD_PESSOAS_FISICAS WHERE CODIGO = V_IDPESSOA;                  
        
                    --INSERI O PROTOCOLO NA TABELA SIACOL_PROTOCOLO;
                    INSERT INTO SIACOL_PROTOCOLOS 
                        (   ID,
                            NO_PROTOCOLO,
                            NO_PROCESSO,
                            FK_SITUACAO_PROTOCOLO,
                            FK_DEPARTAMENTO,
                            OBSERVACAO,
                            FK_ASSUNTO,
                            DT_CADASTRO,
                            FK_INTERESSADO,
                            FK_ASSUNTO_SIACOL,
                            DS_INTERESSADO,
                            DS_ASSUNTO,
                            FK_RESPONSAVEL,
                            DS_RESPONSAVEL,
                            DT_SIACOL, 
                            DS_TIPO_ASSUNTO,
                            IMPORTADO, 
                            ATIVO,
                            DIGITALIZADO) 
                    SELECT  SQ_SIACOL_PROTOCOLOS.NEXTVAL,
                            V_PROTOCOLO.NUMERO,
                            V_PROTOCOLO.PROCESSO,
                            V_SITUACAOPROTOCOLO,
                            VMOVI.FK_ID_DESTINO_DEPARTAMENTOS,
                            NULL,
                            V_PROTOCOLO.FK_ID_ASSUNTOS,
                            V_PROTOCOLO.DATAEMISSAO,
                            V_PROTOCOLO.FK_ID_PESSOAS,
                            NULL,
                            V_NOME,
                            V_ASSUNTO.DESCRICAO,
                            V_IDRESPONSAVEL,
                            V_RESPONSAVEL, 
                            SYSDATE, 
                            V_ASSUNTO.TIPOASSUNTO, 
                            1, 
                            1,
                            V_PROTOCOLO.POSSUI_DIGITALIZACAO
                            FROM DUAL;
                END IF;
        END LOOP;
    RETURN 0;
END ;

/

