-- colunas no siacol_prt_documento para  sinalizar quando um documento é assinado e um hash que aguardará a assinatura
ALTER TABLE SIACOL_PRT_DOCUMENTO ADD (ASSINADO NUMBER(1), HASH VARCHAR2(255) );

-- STATUS DA TIME LINE DAS AÇÕES
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (1, 'ENTRADA', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (2, 'RECEBIMENTO', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (3, 'MUDANÇA DE STATUS', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (4, 'DISTRIBUIÇÃO', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (5, 'TRAMITAÇÃO', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (6, 'CLASSIFICAÇÃO', 1);
INSERT INTO SIACOL_TIPO_HIST_PROTOCOLO (ID, DESCRICAO, ATIVO) VALUES (7, 'CRIAÇÃO DE DOCUMENTO', 1);

-- AINDA NÃO FOI CRIADO
ALTER TABLE SIACOL_HIST_PROTOCOLO ADD (FK_RESPONSAVEL NUMBER, DS_RESPONSAVEL VARCHAR2(255) );

