package br.org.crea.commons.validsigner.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import br.org.crea.commons.validsigner.model.ObjectFactory;
import br.org.crea.commons.validsigner.model.SignerParametersValid;
import br.org.crea.commons.validsigner.model.SignerResultValid;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalSignerWS", targetNamespace = "http://ws.web.pad.cd.valid.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalSignerWS {


    /**
     * 
     * @param signerParameters
     * @return
     *     returns br.com.valid.cd.pad.web.ws.SignerResult
     */
    @WebMethod
    @WebResult(name = "signerResult", partName = "signerResult")
    public SignerResultValid externalPosSignCMS(
        @WebParam(name = "signerParameters", partName = "signerParameters")
        SignerParametersValid signerParameters);

    /**
     * 
     * @param signerParameters
     * @return
     *     returns br.com.valid.cd.pad.web.ws.SignerResult
     */
    @WebMethod
    @WebResult(name = "signerResult", partName = "signerResult")
    public SignerResultValid externalPreSignCMS(
        @WebParam(name = "signerParameters", partName = "signerParameters")
        SignerParametersValid signerParameters);

}
